version: '3.7'

services:
  ##Falta crear la imagen correcta con docker compose
  ##Falta crear el archivo con las variables correctas
  ##Falta verificar cuales son los archivos de ejecucion de gunicorn 
  ## correrlo
  app:
    image: proyecto-ps
    restart: always
    container_name: app
    volumes:
      #Modficar al volumen del proyecto del equipo
      - ./ProyectoProgramacion1:/code
    depends_on:
      - bd
    environment:
      #Varibales de entorno del proyecto definidas en el conf.env
        SECRET_KEY: ${SECRET_KEY}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        BD_NAME: ${BD_NAME}
        BD_USER: ${BD_USER}
        BD_HOST: ${BD_HOST}
        BD_PORT: ${BD_PORT}
    ##Cantidad de recursos en el despliegue
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "1024M"        

  bd:
    ##Imagen de la bd #despliegue mariadb 
    image: mariadb
    restart: always
    environment:
      ##Contraseña de mariadb ##la define el contenedor
      ## la BD_NAME no se que sea
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${BD_NAME}
    volumes:
      ##Volumen de la BD local, la ruta local se copia a data
      - ./data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "1024M"              
      
  web:
    image: nginx
      # restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      ##Volumenes para nginx
      - ./nginx:/etc/nginx/conf.d
      - ./ProyectoProgramacion1/static:/static
      - ./certs:/certs 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "1024M"         
