# Generated by Django 3.2.18 on 2023-05-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_auto_20230529_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP_T',
            new_name='OTP',
        ),
    ]
