# Generated by Django 3.2.18 on 2023-06-13 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_rename_otp_t_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAdmin',
        ),
        migrations.AddField(
            model_name='otp',
            name='tiempo_exp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registroadmin',
            name='contraseña',
            field=models.CharField(max_length=106),
        ),
    ]
