# Generated by Django 3.2.18 on 2023-06-13 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_auto_20230613_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('server_name', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=10)),
                ('disco', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='registroadmin',
            name='ip_server',
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.registroadmin')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.servidores')),
            ],
        ),
    ]
