# Generated by Django 4.2 on 2023-06-18 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_alter_servidores_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='ip_servidor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='asociado',
            name='nombre_registro_admin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='registro_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.registroadmin'),
        ),
        migrations.AlterField(
            model_name='servidores',
            name='cpu',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidores',
            name='disco',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidores',
            name='ram',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
