# Generated by Django 3.2.18 on 2023-05-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_rename_otp_t_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=64)),
                ('otp', models.CharField(max_length=10)),
                ('tiempo_exp', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
