# Generated by Django 3.2.18 on 2023-05-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_auto_20230531_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP_p',
            new_name='OTP',
        ),
    ]
