# Generated by Django 3.2.18 on 2023-05-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='opt',
            new_name='otp',
        ),
    ]
