# Generated by Django 3.2.18 on 2023-05-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_rename_opt_otp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=64)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('id_telegram', models.CharField(max_length=64)),
                ('contraseña', models.CharField(max_length=64)),
                ('ip_server', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
