# Generated by Django 3.2.18 on 2023-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_auto_20230613_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=106)),
            ],
        ),
    ]
