# Generated by Django 3.2.18 on 2023-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('intentos', models.PositiveIntegerField()),
                ('fecha_ultimo_intento', models.DateTimeField()),
            ],
        ),
    ]
