# Generated by Django 4.2 on 2023-06-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0009_loginadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidores',
            name='cpu',
            field=models.CharField(max_length=40),
        ),
    ]
